version: '3.8'

services:
  titanic-api:
    build:
      context: .
      dockerfile: titanic-api/dockerfile
    image: titanic-api:latest
    container_name: titanic-api
    # если убрать порт то внешнему пользователю api стала недоступна
    # ports:
    #   - "500:5000"
    volumes:
      - ./titanic-api/model.pkl:/app/model.pkl

  streamlit-web:
    build:
      context: .
      dockerfile: streamlit-service/dockerfile
    image: streamlit-service:latest
    container_name: streamlit-service
    # внешний порт веб
    ports:
      - "8000:8501"
    volumes:
      - ./streamlit-service/streamlit_app.py:/app/streamlit_app.py